Mana = Mana or {}

if CLIENT then
    include("mana/sh_meta.lua")
    include("mana/sh_config.lua")
    include("mana/cl_hud.lua")
    include("mana/cl_net.lua")
    include("mana/cl_stats.lua")
    
else
    AddCSLuaFile("mana/sh_meta.lua")
    AddCSLuaFile("mana/cl_hud.lua")
    AddCSLuaFile("mana/cl_net.lua")
    AddCSLuaFile("mana/sh_config.lua")
    AddCSLuaFile("mana/cl_stats.lua")
    include("mana/sh_meta.lua")
    include("mana/sh_config.lua")
    include("mana/sv_net.lua")
    include("mana/sv_sql.lua")
    include("mana/sv_meta.lua")
    resource.AddFile( "materials/gonzo/damage.vtf" )
    resource.AddFile( "materials/gonzo/health.vtf" )
    resource.AddFile( "materials/gonzo/resistance.vtf" )
    resource.AddFile( "materials/gonzo/speed.vtf" )
    resource.AddFile( "materials/lda.png" )
    resource.AddFile("materials/reroll/background_hexa.png")
    resource.AddFile("materials/reroll/lancer.png")
    resource.AddFile("materials/reroll/close.png")
    resource.AddFile("materials/reroll/wiphexa.png")
    resource.AddFile("materials/reroll/grimoire.png")
    resource.AddFile("materials/magies/Magie-Amour.png")
    resource.AddFile("materials/magies/Magie-Anti-magie.png")
    resource.AddFile("materials/magies/Magie-Astral.png")
    resource.AddFile("materials/magies/Magie-Bestial.png")
    resource.AddFile("materials/magies/Magie-Brume.png")
    resource.AddFile("materials/magies/Magie-Controle.png")
    resource.AddFile("materials/magies/Magie-Corruption.png")
    resource.AddFile("materials/magies/Magie-Cremation.png")
    resource.AddFile("materials/magies/Magie-Cristal.png")
    resource.AddFile("materials/magies/Magie-Celeste.png")
    resource.AddFile("materials/magies/Magie-Desintegration.png")
    resource.AddFile("materials/magies/Magie-Eau.png")
    resource.AddFile("materials/magies/Magie-Etoile.png")
    resource.AddFile("materials/magies/Magie-Explosion.png")
    resource.AddFile("materials/magies/Magie-Feerique.png")
    resource.AddFile("materials/magies/Magie-Feu.png")
    resource.AddFile("materials/magies/Magie-Fils.png")
    resource.AddFile("materials/magies/Magie-Foudre-noir.png")
    resource.AddFile("materials/magies/Magie-Foudre.png")
    resource.AddFile("materials/magies/Magie-Gaz.png")
    resource.AddFile("materials/magies/Magie-Glace.png")
    resource.AddFile("materials/magies/Magie-Gravite.png")
    resource.AddFile("materials/magies/Magie-Illusion.png")
    resource.AddFile("materials/magies/Magie-Incandescente.png")
    resource.AddFile("materials/magies/Magie-Infini.png")
    resource.AddFile("materials/magies/Magie-Infernal.png")
    resource.AddFile("materials/magies/Magie-Invocation-armes.png")
    resource.AddFile("materials/magies/Magie-Jugement.png")
    resource.AddFile("materials/magies/Magie-Lumiere.png")
    resource.AddFile("materials/magies/Magie-Lune.png")
    resource.AddFile("materials/magies/Magie-Mercure.png")
    resource.AddFile("materials/magies/Magie-Miroir.png")
    resource.AddFile("materials/magies/Magie-Musique.png")
    resource.AddFile("materials/magies/Magie-Metal.png")
    resource.AddFile("materials/magies/Magie-Neige.png")
    resource.AddFile("materials/magies/Magie-Ombre.png")
    resource.AddFile("materials/magies/Magie-Os.png")
    resource.AddFile("materials/magies/Magie-Pictural.png")
    resource.AddFile("materials/magies/Magie-Piege.png")
    resource.AddFile("materials/magies/Magie-Plante.png")
    resource.AddFile("materials/magies/Magie-Poison.png")
    resource.AddFile("materials/magies/Magie-Renforcement.png")
    resource.AddFile("materials/magies/Magie-Roche.png")
    resource.AddFile("materials/magies/Magie-Sable.png")
    resource.AddFile("materials/magies/Magie-Sang.png")
    resource.AddFile("materials/magies/Magie-Soin.png")
    resource.AddFile("materials/magies/Magie-Soleil.png")
    resource.AddFile("materials/magies/Magie-Songe.png")
    resource.AddFile("materials/magies/Magie-Spirit.png")
    resource.AddFile("materials/magies/Magie-Stellaire.png")
    resource.AddFile("materials/magies/Magie-Temps.png")
    resource.AddFile("materials/magies/Magie-Tenebre.png")
    resource.AddFile("materials/magies/Magie-Typhon.png")
    resource.AddFile("materials/magies/Magie-Teleportation.png")
    resource.AddFile("materials/magies/Magie-Vent.png")
    
end